#!/usr/bin/env bash
# Transfer a file from our client to a server
# Run this command on the terminal- scp "fileName" ubuntu@"IP":/home/ubuntu
# Or this command on the terminal- scp -i  ~/.ssh/school "fileName" ubuntu@"IP":/home/ubuntu
# variables
path="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
filename=$(basename "$BASH_SOURCE")
brown='\e[0;33M'
reset='\033[0m'
file="$1"
ip="$2"
user="ubuntu"
key="~/.ssh/school"

if [ $# -eq 2 ]; then
    scp -i "$key" -o StrictHostKeyChecking=no "$path"/"$file" "$user"@"$ip":/home/"$user"/
else
    echo -e "Usage: ${brown}$filename PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY${reset}"
fi
