#!/usr/bin/env bash
# Performing a 301 moved permanently

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Isek7 permanent;"

# Using the variable in sed command
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Testing Nginx configurations
sudo nginx -t
sudo service nginx restart
