#!/usr/bin/env bash
# customizing a 404 page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Isek7 permanent;"

# Using the variable in sed command
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# creating a 404 error page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var/www/html;\n\tinternal;\n\t}"

sudo sed -i "s|listen 80 default_server;|$string_for_replacement|" /etc/nginx/sites-enabled/default

# Testing Nginx configurations
sudo nginx -t
sudo service nginx restart
