#!/usr/bin/env bash
# Configuring web-01 to have an HTTP response header

# Updating packages
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start

# Creating an index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a redirection 
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Isek7 permanent;"

# Using the variable in sed command
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Creating a custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Custom HTTP response header
sudo sed -i "/server_name _;/a \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Testing for syntax errors
sudo nginx -t

# Restart nginx
sudo service nginx restart
