#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend Isek7_frontend
    bind *:80
    mode http
    default_backend Isek7_backend

backend Isek7_backend
    balance roundrobin
    server 477798-web-01 54.172.219.93:80 check
    server 477798-web-02 54.237.102.1:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the HAProxy service
sudo service haproxy restart
