#!/usr/bin/env bash
# A script that tells the story of passwd

file="/etc/passwd"

while IFS=' ' read -r line
do
	username=$( echo "$line" | cut -d ":" -f 1 )
	groupid=$( echo "$line" | cut -d ":" -f 4 )
	home=$( echo "$line" | cut -d ":" -f 6 )
	shell=$( echo "$line" | cut -d ":" -f 7 )
	userid=$( echo "$line" | cut -d ":" -f 3 )
	password=$( echo "$line" | cut -d ":" -f 2 )
	useridinfo=$( echo "$line" | cut -d ":" -f 5 )
	
	echo "The user $username is part of the $groupid gang, lives in $home and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $useridinfo"
done < "$file"
