#!/usr/bin/env bash
# This script prints numbers from 1-20 with a twist inside

i=1

while [ "$i" -le 20 ]
do
	echo "$i"

	case $i in
		4 )
			echo "bad luck from China"
			(( i++ )) ;;
		9 )
			echo "bad luck from Japan"
			(( i++ )) ;;
		17 )
			echo "bad luck from Italy"
			(( i++ )) ;;
		* )
			(( i++ )) ;;
		esac
done
