#!/usr/bin/env bash
# A script that give information about a file

file_name=school

if [ -e $file_name ]
then
	echo "school file exists"
	if [ -s $file_name ]
	then
		echo "school file is not empty"	
	else
		echo "school file is empty"
	fi

	if [ -f $file_name ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
