#!/usr/bin/env bash
# A script that configures an Ubuntu server with new IP redirections

cp /etc/hosts ~/hosts.tmp
sed -i 's/^127\.0\.0\.1.*$/127.0.0.2	localhost/' ~/hosts.tmp
echo '8.8.8.8         facebook.com' >> ~/hosts.tmp
cat ~/hosts.tmp > /etc/hosts
