#!/usr/bin/env bash
# return a page containing 'Hello Holberton' when querying the root of it

apt-get install apache2 -y
service apache2 start
echo "Hello Holberton" > /var/www/html/index.html
echo "ServerName localhost" >> /etc/apache2/apache2.conf
