#!/usr/bin/env bash

# Specify the full path for the private key file
private_key="/root/.ssh/school"

# Specify the number of bits for the key
bits=4096

# Specify the passphrase for the key
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $bits -f $private_key -N $passphrase

# Display information about the generated key pair
echo "Generating public/private rsa key pair."
echo "Your identification has been saved in $private_key."
echo "Your public key has been saved in $private_key.pub."
echo "The key fingerprint is:"
ssh-keygen -lf $private_key | awk '{print $2}'
echo "The key's randomart image is:"
ssh-keygen -lvf $private_key | tail -n +2

# List the files in the current directory
ls -l
